### ISSUE TITLE
Issue 6: For Milestone 3 ; Training the Model

### ISSUE THREAD

**Issue by Crisnzano** [Crisnzano/BI-Loan-Appraisal-Project#6]
- [x] Data splitting
- [x] Bootstrapping 
- [x] Cross validation (basic, repeated or LOOCV)
- [x] Model training for classification, regression, association or clustering
- [x] Model performance comparison using resamples

**Comment by Crisnzano** [comment]
Closed after Training the model and doing a comparison using resamples. Linear Discriminant Analysis was found to be the model with the highest accuracy. Therefore it is the model of choice.
